permalink: /:title/
collections:
  prototypes:
    output: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      scripts: "cookie.html"
  -
    scope:
      path: ""
      type: "prototypes"
    values:
      layout: "prototype"
sass:
  style: compressed
include: 
  - __settings__.js
  - __modules__.js
  - __start__.js
  - __loading__.js
  - __game-scripts.js